update docs, template parameters
aws-quickstart/quickstart-ct-newrelic-one pull request #24
Opened 2021-06-02 01:11 UTC by rohitkaul83

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-06-02 02:02 UTC, wellsiau-aws commented
tested PR on local, looks good.

2021-06-02 18:21 UTC, sshvans requested changes

2021-06-02 18:21 UTC, sshvans commented on templates/newrelic-stack-set.yml
> +    Description: Your New Relic account ID
Please don't use "Your". It is self-explanatory that user needs to enter their account id and not someone elses ;)

2021-06-02 18:21 UTC, sshvans commented on templates/control-tower-customization.template.yml
> +    Description: Your New Relic account ID. See https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/account-id/
Please don't use "Your". It is self-explanatory that user needs to enter their account id and not someone elses ;)

2021-06-07 23:01 UTC, sshvans approved these changes

2021-06-07 23:01 UTC, merged